version: "2.4"

services:
  api:
    build:
      context: .
      args:
        - NODE_ENV=production
    env_file:
      - .env
    command: npm run start
    ports:
      - ${PORT}:${PORT}
    networks:
      - dev
    depends_on:
      - redis
  redis:
    image: redis:6-alpine
    volumes:
      - dev-redis-data:/data
    networks:
      - dev
    ports:
      - 6379:6379

volumes:
  dev-redis-data:
networks:
  dev:
    external: true
